// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/jmoiron/sqlx"
	"github.com/lp9087/go_otello_dashboard_api/internal/usecase"
	"github.com/lp9087/go_otello_dashboard_api/internal/usecase/repository"
)

// Injectors from wire.go:

func InitializeFirstDashboardUseCase(db *sqlx.DB) *usecase.FirstDashboardUseCase {
	pgFirstDashboardRepo := repository.NewPGFirstDashboardRepo(db)
	firstDashboardUseCase := usecase.NewFirstDashboardUseCase(pgFirstDashboardRepo)
	return firstDashboardUseCase
}
