// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/lp9087/go_otello_dashboard_api/internal/usecase"
	"github.com/lp9087/go_otello_dashboard_api/internal/usecase/repository"
	"github.com/lp9087/go_otello_dashboard_api/pkg/postgres"
)

// Injectors from wire.go:

func InitializeMostLoyalHotelsUseCase(pg *postgres.Postgres) *usecase.MostLoyalUseCase {
	pgMostLoyalHotelsRepo := repository.NewPGMostLoyalHotelsRepo(pg)
	mostLoyalUseCase := usecase.NewMostLoyalHotelsUseCase(pgMostLoyalHotelsRepo)
	return mostLoyalUseCase
}
