// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dashboard/mostLoyalHotels": {
            "get": {
                "description": "Show all dashboards mostLoyalHotels",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Show mostLoyalHotels",
                "operationId": "mostLoyalHotels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/v1.loyalHotelsResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.MostLoyalHotels": {
            "type": "object",
            "properties": {
                "externalID": {
                    "type": "string"
                },
                "hotelName": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "rates": {
                    "type": "integer"
                },
                "roomTypes": {
                    "type": "integer"
                },
                "totalAmount": {
                    "type": "integer"
                }
            }
        },
        "v1.loyalHotelsResponse": {
            "type": "object",
            "properties": {
                "mostLoyalHotels": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.MostLoyalHotels"
                    }
                }
            }
        },
        "v1.response": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "message"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
